### ISSUE TITLE
LastPass issue on Windows

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10682]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Couple of reports from community on Lastpass not working on Windows 
https://community.brave.com/t/lastpass-on-windows-doesnt-work/6436/15

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 

- Brave Version (revision SHA):
Brave	0.18.23
rev	36ae2ec
Muon	4.3.10

- Screenshot if needed:

- Any related issues:
cc: @jonathansampson

**Comment by pasme** [comment]
after installing brave 0.18.23 on windows 10, there is no trace of both lastpass and pdf viewer on the extension menu.
we can select last pass on password management menu, but preference page lead to nowhere. 
No trace also of the install files on program menu.
works properly on other laptop with windows 7.

**Comment by jonathansampson** [comment]
@pasme Can you update again and see if these issues are still present?

**Comment by pasme** [comment]
Thanks for the update.
no changes with the last version, i have cleaned all files and restart before installing

Name | Version
-- | --
Brave | 0.18.29
rev | 85f059d
Muon | 4.3.16
libchromiumcontent | 60.0.3112.113
V8 | 6.0.286.56
Node.js | 7.9.0
Update Channel | dev
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

I can select it from the password menu, but Lastpass is still absent from the system files,  no support page.

![image](https://user-images.githubusercontent.com/31563514/30228614-c92be1fe-94de-11e7-8b5c-a42259f02899.png)

I will try a new windows install from scratch, as my version has been updated from 7.

once again thanks for support.

**Comment by jonathansampson** [comment]
@pasme I wanted to check-in and see if there were any developments on your end. Thanks!

What is your username on this machine? [Does it contain any non-ASCII characters](https://github.com/brave/browser-laptop/issues/9425)?

**Comment by pasme** [comment]
Hello,

yes my profile has a 'é', so non ascii i think.
i did not pay attention to that, i am going to update it this week and i
come back to you.

Seb

2017-09-17 20:10 GMT+02:00 Sampson <notifications@github.com>:

**Comment by pasme** [comment]
Hello,

After a new windows install,
- user login without non ascii caracter
a with the latest brave version everything is solved...

2017-09-17 22:38 GMT+02:00 Sébastien Ferrand <sj.ferrand@gmail.com>:

**Comment by pasme** [comment]
and thanks for support!

2017-09-17 20:10 GMT+02:00 Sampson <notifications@github.com>:

**Comment by traderd65** [comment]
After some use of the lastpass extension, it stops working and just displays a dormant popup at the bottom right corner of the browser. Disabling and re-enabling the extension doesn't help, only restarting the browser.
<img width="323" alt="about_brave" src="https://user-images.githubusercontent.com/1514731/35921356-5f5b5904-0be8-11e8-8ef9-548c77b63670.png">
<img width="446" alt="lastpass_dormant_window" src="https://user-images.githubusercontent.com/1514731/35921364-64f400d2-0be8-11e8-9376-0d2625984635.png">

**Comment by yacuzo** [comment]
I still have this. I have an 'é' in my user account name. 
 
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Comment by bsclifton** [comment]
@yacuzo would you be willing to try our Beta? This is a different code-base, so you'd need to import your settings (most everything should import). You can try it here:
https://brave.com/download-beta

**Comment by yacuzo** [comment]
Yea, it works in the beta.
