### ISSUE TITLE
browser crash/lockup when typing into URL bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12975]
Multiple reports from [community ](https://community.brave.com/t/crash-after-first-letter-in-new-tab-address-bar/15118) regarding browser crash when typing in a url

>Just updated to latest version. As soon as I press ctrl-T to open a new tab and type 1 letter of my domain name in the address bar, the entire browser locks up and I have to end task.

cc: @bridiver @darkdh @bsclifton

**Comment by pongraczi** [comment]
For me, when I open a new tab and start typing the url, brave gets unresponsible for long time (10+ seconds) and produce high cpu usage. Probably related.
This is after upgrading to the new version. Details below.

Here you can see it in action:

![slow](https://user-images.githubusercontent.com/5891983/35728303-733a4b5a-080b-11e8-9455-063c83c24138.gif)

 
Brave: 0.20.29 
V8: 6.4.388.40 
rev: 4fc3c8ff3bcb6af75088b125e00d3a70382b9bec 
Muon: 4.7.9 
OS Release: 4.13.0-32-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Comment by srirambv** [comment]
Could you try upgrading to the latest version 0.20.30 and see if this is fixed for you

**Comment by pongraczi** [comment]
It seems, my problem solved by the latest version. Thanks!
 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 4.13.0-32-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Comment by arjenbokhoven** [comment]
For me, this issue happened actually after upgrading to the latest version.

Brave | 0.20.30
V8 | 6.4.388.40
rev | 8b78402
Muon | 4.7.9
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Comment by darkdh** [comment]
If someone suffer from this issue can send the session file to us, that would be really helpful for us to fix it quickly.

session file might contains private data like `browsing history`, `bookmark`, opening `tabs` and `windows`...etc
Make sure you clear those data before sending.
The data in session file specified in https://github.com/brave/browser-laptop/blob/e7f7c8283e644eb747ba0a8099c57160ca052cd9/docs/state.md

If you are willing to send session file to us, you can find the file in 
```
Windows: %appdata%\brave\session-store-1
macOS: ~/Library/Application\ Support/Brave/session-store-1
linux: ~/.config/brave/session-store-1
```
And please send the file to anthony@brave.com, really appreciated it

**Comment by capouch** [comment]
I can confirm issue is still there in 0.20.30.  I just sent a session file to the above address.

Linux Slackware running as a VM under Virtualbox, specifics upon request if needed . . .

**Comment by capouch** [comment]
Update: I will test more later, but I was astounded after I exited the browser "for the day," forgot something and launched again, and now the matcher in the search bar appears to be working just fine!!

**Comment by capouch** [comment]
Is it possible this only hits on the first time you're upgrading from 19?

**Comment by onmyouji** [comment]
It seems that's the case, I can't reproduce the problem after restarting the browser. It only happened the first time after upgrading.

**Comment by pongraczi** [comment]
From my side, it happened at the first time running after upgrading 19->20.

**Comment by ashrafhadden** [comment]
This ONLY happens for me when I have "Show history matches" turned on under "Preferences>Search Bar Options". I have every other Search Bar Option turned on and it works just fine. Perhaps an inefficient searching/query algorithm?
![2018-02-10 08 39 15 pm](https://user-images.githubusercontent.com/32565770/36068477-d1bc5ad4-0ea4-11e8-91a4-7a4e10962692.png)

**Comment by kenneho** [comment]
I have the same issue as @ashrafhadden, on both my Windows 10 and Ubuntu Budgie laptop. 

My Windows 10 Brave specs: 
 ` 
Brave: 0.23.104 
V8: 6.8.275.24 
rev: b454a4a99934c4aa27fbe2effc5f72ce92e3266b 
Muon: 8.0.8 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84`

**Comment by utk4rsh** [comment]
Facing the same on the latest install. Installed the latest and imported everything from chrome.

**Comment by kenneho** [comment]
My understanding is that the Brave Beta version will replace the current one pretty soon, and this issue does not exist on the beta version. Maybe migrate to Brave Beta instead of using the soon to be deprecated version?

**Comment by bsclifton** [comment]
Hi folks

I would definitely recommend moving over to the Beta version of the app, as we won't be investigating/fixing this problem with the `browser-laptop` code-base.  You can download it here:
https://brave.com/download-beta

(stable should be coming soon and then we'll eventually deprecate `browser-laptop` entirely)
