### ISSUE TITLE
Two finger swipe for backwards/forwards does not work in C65

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#13433]
### Description
On macOS or other laptops, you can use a gesture to go backwards and forwards in your page history. This is a two finger swipe which you do to either left or right. If the input is not registering, you can go into Advanced > Swipe Options to adjust the sensitivity

With the Chromium 65 upgrade, this functionality was broken

### Steps to Reproduce

  1. Be on a laptop with a trackpad
  2. Visit brave.com
  3. Click a link, so your back button is enabled (ex: you're able to go back)
  4. Do two finger swipe from left to right (this should be going back)

**Actual result:**
nothing happens

**Expected result:**
back button should get large (to indicate swipe was registered) and page should navigate back

**Reproduces how often:**

100%

### Brave Version
0.21.x-C65
**about:brave info:**

**Reproducible on current live release:**

No

**Comment by LaurenWags** [comment]
Two finger swipe does not work all the time.
STR (reproduced by @kjozwiak also):

**Comment by darkdh** [comment]
That is the different issue. same cause as https://github.com/brave/browser-laptop/issues/13368
once https://github.com/brave/browser-laptop/issues/13368 fixes, the click problem goes away

**Comment by LaurenWags** [comment]
Retest scenario from https://github.com/brave/browser-laptop/issues/13433#issuecomment-373149458 once https://github.com/brave/browser-laptop/issues/13368 is resolved as noted by @darkdh

**Comment by srirambv** [comment]
This is macOS specific correct?

**Comment by darkdh** [comment]
@sriambv, yes

**Comment by kjozwiak** [comment]
I can still reproduce the https://github.com/brave/browser-laptop/issues/13433#issuecomment-373149458 case with `0.21.658` ad8bdc1d4f9c175d37dd9d4bb1b93dd0be512a1f which includes the #13368 fix. However, it's also reproducible in `0.21.18` 580be782bc37ed8580dd22f79e1d2d355fddfb89 which is the latest release so I'm not 100% sure if this is a real issue.

@bsclifton @darkdh thoughts? The underlying issue has been fixed, however, whenever you switch focus to another application and return to brave, you'll have to click on the page before you can start swiping through the pages. This only affects users that switch context, come back to brave and start swiping right away without interacting with brave.

**Comment by kjozwiak** [comment]
@LaurenWags mind taking a look at this as well? Would be good to get another set of eyes on it.

**Comment by LaurenWags** [comment]
LGTM @kjozwiak 👍

**Comment by kjozwiak** [comment]
Awesome, thanks for double checking @LaurenWags! Always good to have another pair of 👀 !
