### ISSUE TITLE
Dragging a tab to blank tab bar area results in lost tab

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#14046]
### Steps to Reproduce ONE

  1. Create two windows, one with 6 tabs, and one in 1 (or 2 or 3 or 4) tabs.
  2. Drag the 6th tab to the blank area of the tab bar in the other window, being careful never to drag over the single tab in that window

**Actual result:**
Tab never shows up

**Expected result:**
Tab shows up at end of tab set

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

**Reproducible on current live release:**
Probably but possibly different (similarly broken) results.

**Comment by petemill** [comment]
Should be fixed with next release

**Comment by srirambv** [comment]
@petemill dragging tab into empty space in tabs bar causes it to open up as a new window. Below is the recording

![14046](https://user-images.githubusercontent.com/17010094/39927448-3d599562-5500-11e8-99fb-82a96e007d58.gif)

However this is not the same behaviour on macOS. Is the fix only for mac or for all platforms?

**Comment by LaurenWags** [comment]
On macOS the tab dragged to the empty area of the tabs bar is added to the window:
![14046-2](https://user-images.githubusercontent.com/28145373/39928176-a1528e1e-5502-11e8-9b5b-5f882f9502dc.gif)

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.709 e043144
* muon 6.0.9
* libchromiumcontent 66.0.3359.139

**Comment by srirambv** [comment]
Still an issue on windows. Doesn't drop on the empty space in tabsbar after the new tab sign. 
![14046_1](https://user-images.githubusercontent.com/17010094/39943399-b46cc694-5530-11e8-98ad-56b81a81e497.gif)

**Comment by srirambv** [comment]
Tab only drops before the new tab button resizing the last existing tab or if its dropped in between two tabs it resizes the right tab and then drops in.

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/browser-laptop/issues/14099 which is windows specific issue

**Comment by bsclifton** [comment]
Removing milestone since this appears to be a duplicate of https://github.com/brave/browser-laptop/issues/14099
