### ISSUE TITLE
Ask for permission when opening a window via window.open (allow a per-site preference for popups)

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#3752]
**Describe the issue you encountered:**
In FF and Chrome there is an option to allow or disable annoying window popups, opened by window.open, which are mostly used for advertisements and clickbaits. Brave currently don't have such option.

**Expected behavior:**

When window.open is used with URL different than the domain you are currently on, a notification to Allow or Deny the action should be present, just like when you need to give a permission for flash or fullscreen. Also it will be good if there is a global option in bravery panel to disable this as well for all websites.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  0.12.0
- Steps to reproduce:
  1. N/A
- Screenshot if needed:
- Any related issues: #94

**Comment by patrick99e99** [comment]
+1 ... I am a developer, and for example am trying to delete an index for elasticsearch in my browser client, and it does so by popping up an alert window to confirm I want to delete the index.. But in brave this never shows up, so I cannot use Brave for this and have to use a different browser :(

**Comment by bsclifton** [comment]
This is a really important one; huge +1 from me

**Comment by JamborJan** [comment]
Is there any commitment from the core dev team to deliver such a feature?

**Comment by bbondy** [comment]
@JamborJan yes, we will deliver this feature.

**Comment by bsclifton** [comment]
+1 from @jemspatel in https://github.com/brave/browser-laptop/issues/3143

>   1. open site http://popuptest.com/
>  2. click on Multi-PopUp Test 
>  3. no popup open

**Comment by bsclifton** [comment]
Lots of +1's from https://github.com/brave/browser-laptop/issues/2677

**Comment by bsclifton** [comment]
+1 from https://github.com/brave/browser-laptop/issues/3777

**Comment by hugobuddel** [comment]
+1 plesk phpmyadmin link opens in a new window, so it appears to do nothing in Brave. (Yeah, Plesk behaves badly, but have to use it.)

Silently blocking popups is mainly relevant for sites of which the user does not yet know there should be popups in order to function; it will just appear as if the site is broken. For known cases, like the one described above and many of our 'intranet' pages, I'm happy to use another browser.

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/pop-up-window-in-banking-app-not-appearing/9755/2

**Comment by ISShub** [comment]
Opening a link that states that information is displayed in a new window. If the display of additional windows is currently suppressed by a pop-up blocker, you must first deactivate this setting. Question is which setting do I gotta deactivate??????

**Comment by kristianmandrup** [comment]
I mistakenly activated popup blocker for a page where I need the popups for key functionality.
How do I re-enable popups for that page. Can't seem to find the preference setting. Please make it more clear. Thanks.

**Comment by jv5** [comment]
+1 -- because of this issue, I am forced to use a second browser with a banking site that uses popups. Hard to believe this feature request is like two years old now? I'll be patient. :)

**Comment by awerffeli** [comment]
I am having the same issue. As a developer a need this for certain frameworks that use pop-ups.

**Comment by mstein66** [comment]
Is there a way to add websites to allow pop-ups as my bank requires this and this post and all other posts that refer to this one (3752) by bsclifton doesn't provide any solutions?

**Comment by mijoflan** [comment]
I'm with @mstein66 is there a solution anywhere?!?

**Comment by mijoflan** [comment]
@Sh1d0w is there a solution to this issue or am I missing something in the thread/s?

**Comment by dezryth** [comment]
As far as I'm aware this is still an issue. Let to a frustrating experience today at work. Would love to see progress on this one!

**Comment by su-narthur** [comment]
Hi, everyone. Instead of just posting a "+1", please add a thumb-up on the original issue up top because issues can be sorted by how many thumb-ups they've received.

**Comment by NAO-Projekt-DHBW** [comment]
Soo annoying.. Totally disqualifies "Brave" as a browser for daily work. OTRS (Ticketsystem) does not work reliable at all.

**Comment by Tastaturix** [comment]
Can't work with Brave too, OTRS and Banking Software don't work.

**Comment by BitInspector** [comment]
Still present in Brave 0.22.669.  I've been recommending Brave to non technical friends and family members.  This will push them back to their old browsers.

**Comment by slmeyer** [comment]
I wait patiently - it is not that hard though, to click off the shield for banking sites, OTRS etc. 
As it is remembered through restarts you can even do it for granny when you install it for her :)

**Comment by axelhuizinga** [comment]
Any progress on this serious issue? 0.23.19 and still no new tab 
configurable window.open brave is essential for many business applications
window.open returns:
Window
blur:ƒ ()
close:ƒ ()
closed:true
focus:ƒ ()
frames:null
length:0
location:Location {href: undefined, assign: ƒ, replace: ƒ}
opener:null
parent:null
postMessage:ƒ ()
self:null
top:null
window:null

**Comment by bsclifton** [comment]
Confirmed fixed in [brave-core](https://github.com/brave/brave-browser). Any blocked popups will show in the omnibar

**Comment by guisantos** [comment]
How to enable popup again in a specific website?

**Comment by arkag** [comment]
Chiming in now that it's not working on W10 with Connectwise as the popup creator.

**Comment by jv5** [comment]
I thought this issue was "closed" to further comments, but I see we can still comment. After the reported fix on Sep 3, I still had the same issue on a banking site. Was not fixed for me. Have moved on to another browser, but would like to come back to Brave someday. :)

**Comment by guisantos** [comment]
I'm using the stable version, probably that's why is not working for me.

**Comment by bsclifton** [comment]
`brave-core` is just the internal name we have (opposed to `browser-laptop`, which is this repository on GitHub).  The latest Beta version (which uses the `brave-core` code-base) can be downloaded here:
https://brave.com/download-beta

We'll expecting to have a stable release soon (within 2 weeks) and will then look at an upgrade path for `browser-laptop` => `brave-core`
