### ISSUE TITLE
Findbar lags sometimes losing characters

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#3876]
**Did you search for similar issues before submitting this one?**
Yes. 
**Describe the issue you encountered:**
Sometimes when you open the findbar and start typing there is a noticeable lag before the characters show up. We think it might be blocking on finding all of the characters you typed and perhaps debouncing that query would fix it. 

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux 
macOs

- Brave Version:
0.12.0

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Sh1d0w** [comment]
This is possible related issue #3730

I think online suggestions are causing delay as well, but I haven't digged into the code to check that, decided worth mentioning it here :)

Those suggestions have to be async, not waiting for all of them to complete to show the suggestions list.

**Comment by bbondy** [comment]
@BrendanEich or anyone else that can reproduce, please confirm that while you have it in a state of reproducing (make sure of this first!), can you turn off `preferences -> search -> show tab matches`.  After you do that, does it reproduce?

**Comment by diracdeltas** [comment]
@Sh1d0w @bbondy are your comments relating to the URL bar or the findbar? i don't think the findbar has suggestions.

@jkup is the user input lost, or does it just not show up for some delay?

**Comment by jkup** [comment]
@diracdeltas honestly I'm not sure I've encountered this. I know @BrendanEich has mentioned it a few times and asked me to create an issue.

**Comment by bbondy** [comment]
Brendan has lag with both

**Comment by Sh1d0w** [comment]
@diracdeltas Sorry I've thought of the URL bar, not the FIndbar. I have never had problems with the Findbar, rather than the URL bar (which have a lot of glitches tho, doesn't always autocomplete, text can't be "cut" sometimes etc).

Please ignore my comment in this thread regarding the FIndbar.

**Comment by diracdeltas** [comment]
i definitely see it slower some times than others, but never enough to lose any characters. trying out a fix now.

**Comment by diracdeltas** [comment]
fixed by 27bd13f i think, please reopen if not

**Comment by bradleyrichter** [comment]
I am still losing the "om" in ".com". I see this in both 12.6 and current master.

**Comment by bradleyrichter** [comment]
further sleuthing has revealed an interesting sequence.

@diracdeltas - please DL this GIF and open it in mac preview. Then step through frames 76 - 84.

![missingcharacters_in_url](https://cloud.githubusercontent.com/assets/13509546/19671774/31bf109c-9a3f-11e6-84b3-b2e7c0f9c1e4.gif)

**Comment by Sh1d0w** [comment]
@bradleyrichter it seems it is still happening, but I can not reproduce it. Good you recorded it in a GIF. Now that I am looking into the frames one by one we can clearly see another issue I have reported some time ago https://github.com/brave/browser-laptop/issues/4219

Could be possibly related, or not.

**Comment by bradleyrichter** [comment]
@Sh1d0w It does seem related.

**Comment by diracdeltas** [comment]
@bradleyrichter i'm confused why you reported this here since your screenshot shows the urlbar, not the findbar. can this be closed?

**Comment by bradleyrichter** [comment]
I think a search for URL bar brought this up since it became mixed. I'll make a new issue.
