### ISSUE TITLE
Support U2F Keys

### ISSUE THREAD

**Issue by butlermatt** [brave/browser-laptop#518]
I use a U2F key (YubiKey Neo) for Two factor authentication in locations such as here on github and with Google accounts (as well as Lastpass extension).

While the key works great in Chrome, it's not currently supported in Brave. This is a significant blocker for me. I'd love to see this functionality implemented. See the error I get when trying log into my github account with Brave (at the point where the security key is requested).

![gitu2f](https://cloud.githubusercontent.com/assets/1148886/12721356/cf5c0fee-c8d5-11e5-9b9f-ef2fbf9483dc.png)

**Comment by jmalonzo** [comment]
This might be an issue with electron - https://github.com/atom/electron/issues/3226

**Comment by juniorz** [comment]
When I try to login on Google, it asks me to install this extension: https://chrome.google.com/webstore/detail/gnubbyd/beknehfpfkghjoafdifaflglpjkojoco

But there's no install button.

**Comment by luixxiul** [comment]
@butlermatt, are you still seeing the issue?
@juniorz, you cannot install Chrome's extension to Brave for now. Please see #253

**Comment by butlermatt** [comment]
Yes, totally seeing the same issue still. Same notice as my first message posting. Sorry for the delay in responding I didn't get the notice properly.

**Comment by geekgonecrazy** [comment]
Pretty big blocker for me to be able to switch over fully.  Would it be a matter of just baking in that extension?  Or are there API's its going to need?  Based on that electron issue linked it looks like there might be some missing API's?

**Comment by bridiver** [comment]
It's been a long time since I used a Yubikey, but I thought they acted as a keyboard and just typed in the box? I can take a look at the Chrome extension and see if we support the APIs it requires

**Comment by geekgonecrazy** [comment]
@bridiver from my understanding yes that's essentially what's happening.  I think it does do some checks in the USB HID tree polling for descriptors.

**Comment by bridiver** [comment]
we do want to get this working and I'm looking at the extension, but it's odd because the whole thing seems antithetical to the concept behind yubikeys. They act like a keyboard to avoid the need for any special hardware support. I think I might still have an old one lying around somewhere that I can test with.

**Comment by terribleplan** [comment]
There is a new standard on the block called U2F, and yubikeys can now do
that. It actually performs some crypto to identify you to the site, and as
such there is no way it could simply be a keyboard.

Look into it, it's pretty neat:
https://fidoalliance.org/specifications/overview/

**Comment by geekgonecrazy** [comment]
@bridiver yeah the yubikey that completely acts just like a HID device works no problem.  Its the ones now based on the U2F standard that does a little more then the just pretend to be an HID device.

**Comment by bridiver** [comment]
sounds like my old yubikey will not be helpful then. We don't support all of the chrome extensions apis yet, but if I can get it working with minimal effort we can push it out pretty quickly. If it requires more work we'll have to prioritize and schedule it.
cc @bbondy

**Comment by eamsden** [comment]
There is discussion about adding Chromium's U2F support to Electron at electron/electrion#3226.

**Comment by eamsden** [comment]
I can see the following paths forward
- Hack Electron to expose Chromium's "gnubby" extension that supports U2F/FIDO.
- Hack Electron to expose chrome-hid and copy the "gnubby" code in brave
- Write a new U2F/FIDO drive for brave on top of node-usb
- Write a new Native Node module to bind [libu2f-host](https://developers.yubico.com/libu2f-host/)

**Comment by bridiver** [comment]
at least in theory the only thing you would have to implement to use the extension is`cryptotokenPrivate`. Everything else is provided by `src/extensions`, but there not all of them are in `atom/browser/browser_context_keyed_service_factories.h` and you will likely have to pull in a lot of new dependencies from chrome. You can see @darkdh recent autofill and importer work in https://github.com/brave/electron and https://github.com/brave/libchromiumcontent to see how to add new chrome dependencies

**Comment by eamsden** [comment]
If I read the docs correctly, cryptotokenPrivate is just for the UI to get explicit user permission to register a token with a website. That had to be native in Chromium because it had to show a native toolbar. But all of Brave's UI is JS on top of Electron, right? So it should be fairly easy to implement that and then pull in the rest of the necessary stuff from Chrome?

**Comment by bridiver** [comment]
I didn't look at it closely, but that sounds reasonable. You will definitely have to pull in additional dependencies in libchromiumcontent because we don't current have the hid support enabled in `atom/browser/browser_context_keyed_service_factories.h`. See `extensions/browser/browser_context_keyed_service_factories.h` in libchromiumcontent

**Comment by eamsden** [comment]
OK I'll look into that next time I get some spare hacking time.

**Comment by eamsden** [comment]
How do I pull my changes to libchromiumcontent to electron and Brave?

**Comment by willy-b** [comment]
Somebody else can probably answer this better than me, but if you put browser-laptop, brave-electron, and brave-libchromium content in sibling directories, brave-electron has scripts to help with this.

Given that electron and libchromium are in sibling directories, 
you can run `npm run libchromium-bootstrap` (one-time) and `npm run libchromium-build` (each time) to update brave-electron with your libchromium changes.
Finally, to push the updated brave-electron to browser-laptop, you can use `npm run browser-build` from brave-electron.

**Comment by willy-b** [comment]
(extra detail)

By sibling directories I mean brave/browser-laptop, brave/electron, and brave/libchromiumcontent all share the same parent directory:
```
willy@xeris:~/projs/git/3rd/brave$ ls -1 | grep "electron$\|libchromium\|browser"
browser-laptop
electron
libchromiumcontent
```

All the npm scripts I mentioned are in brave/electron:
```
willy@xeris:~/projs/git/3rd/brave$ cd electron
willy@xeris:~/projs/git/3rd/brave/electron$ cat package.json | grep "\-build\|bootstrap" | grep -v "watch"
    "bootstrap": "python ./script/bootstrap.py",
    "browser-build": "npm run build && rsync -avz --delete out/D/Brave.app ../browser-laptop/node_modules/electron-prebuilt/dist/",
    "libchromium-build": "../libchromiumcontent/script/bootstrap && ../libchromiumcontent/script/update && ../libchromiumcontent/script/build && ../libchromiumcontent/script/create-dist --no_zip",
    "libchromium-bootstrap": "./script/bootstrap.py -v --libcc_source_path ../libchromiumcontent/dist/main/src --libcc_shared_library_path ../libchromiumcontent/dist/main/shared_library --libcc_static_library_path ../libchromiumcontent/dist/main/static_library",
    "browser-build-linux": "npm run build && rsync -avz --delete out/D/ ../browser-laptop/node_modules/electron-prebuilt/dist/",
```

**Comment by bridiver** [comment]
there are several recent PRs with examples of pulling in new deps 

https://github.com/brave/libchromiumcontent/pull/3

**Comment by luixxiul** [comment]
Another requesr: https://community.brave.com/t/closed-fido-2fa-support-please-yubikey-trezor/694?u=suguru

**Comment by diracdeltas** [comment]
+1 from myself

**Comment by jonrh** [comment]
Blocks me from switching from Chrome. Bit of a shame since Brave is so incredibly enticing otherwise!

**Comment by Georgi87** [comment]
Our team is looking into this issue to allow the use of hardware wallets with electron apps. Please contact me if you are working on this too to evaluate the current state of development.

**Comment by diracdeltas** [comment]
As of Chrome 41, the gnubby u2f extension is no longer needed to support u2f, so I think porting the extension is a red herring. Looks like Chrome has native code for doing U2F in src/device/u2f, i wonder if we can just use that.

**Comment by diracdeltas** [comment]
actually i think Chrome 41+ implemented this via the cryptotoken resource, which is like an extension but in Chrome by default. https://cs.chromium.org/chromium/src/chrome/browser/resources/cryptotoken/

**Comment by bbondy** [comment]
@evq do you have cycles to take this?

**Comment by evq** [comment]
@bbondy yes I can take this

**Comment by bridiver** [comment]
@evq just came across something related in chrome_content_browser_client `CreateUsbDeviceManager`

**Comment by kspearrin** [comment]
bitwarden supports U2F login and since Brave's user agent is the same as Chrome there is no way for us to filter it out as unsupported. This causes the U2F screen during login to always show as the default for users that have configured U2F on their account (as opposed to one of their backup methods such as authenticator app).

**Comment by evq** [comment]
Just wanted to give an update to everyone, I have U2F working locally on both linux and mac.

Cross platform testing uncovered a few issues, of which only one remains which unfortunately seems to prevent registration on windows. Once I have resolved this, U2F will go up for PR :)

**Comment by alexwykoff** [comment]
@evq how is this looking for 0.20?

**Comment by tadhgpearson** [comment]
Ironically, because I have U2F on my Github account, I had to open Chrome to add my support for this issue!

**Comment by kylerschin** [comment]
I want da u2f. I prefer Brave for privacy and security purposes, but I really would like to use my Ledger Wallet to Auth to Github.

**Comment by rucuriousyet** [comment]
Take a look at https://github.com/flynn/u2f... Its a pretty good library (written in pure Go) that might help you create a mostly if not completely node based u2f extension for Brave...

**Comment by ferologics** [comment]
@evq any update on the windows registration issue?

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/please-install-fido-u2f-functionality-as-soon-as-you-can/11384?u=eljuno

**Comment by esc** [comment]
+1 can help with testing

**Comment by 164-dame** [comment]
Just a side note, as a (important point here) -----> _Privacy_ based browser, it is __essential__ to support fido u2f. Not only yubikeys but also treor and thetis among others have fido u2f products, and I feel that I should be able to use them in my browser of choice. ❤️

**Comment by jazerix** [comment]
Come on guys. This is literally the only thing holding me off from switching. It's 2018, you guys are getting traction, please implement this :)

**Comment by rucuriousyet** [comment]
I could implement this in golang but I'm not sure how we could integrate
this into electron... It would be pretty each to use golang via cgo as if
it were a c shared lib. Any interest here?

-sent from my OnePlus X

**Comment by rucuriousyet** [comment]
More than willing to make a contribution here if needed.

-sent from my OnePlus X

**Comment by diracdeltas** [comment]
hi everybody, the U2F support pull request was recently merged into Muon: https://github.com/brave/muon/pull/268

eV is busy with BAT grant work right now, but this is mostly done now

**Comment by diracdeltas** [comment]
@rucuriousyet and others, thanks for offering to help! there are some follow-up issues in https://github.com/brave/muon/pull/268.

For testing U2F support, I think it may already work on Brave master (not sure). If not, you can build Muon on a branch that includes https://github.com/brave/muon/pull/268 and start Brave with that custom Muon build. instructions in https://github.com/brave/browser-laptop-bootstrap

**Comment by okiess** [comment]
Just tried it on my 0.19.139 installation on MacOS and it doesn't work yet.

**Comment by cannedshrimp** [comment]
Also had issues today with U2F on the current standard version of Brave. Worked fine in Chrome.

**Comment by Liunkae** [comment]
Support for U2F keys is currently set for the next scheduled release, 0.20.x Hotfix 2. (PR #10530)

**Comment by bsclifton** [comment]
Quick update on this:
It won't ship with our next release... but it IS available for testing now 😄 👍 

Please check out our Beta channel...
https://github.com/brave/browser-laptop/releases/tag/v0.21.9beta

Help testing this would be very much appreciated 😄

**Comment by evq** [comment]
@chmanie No, we don't have a flag - it should be automatically enabled. I did some testing and I am investigating the possibility of a platform specific issue. What OS are you using?

**Comment by cannedshrimp** [comment]
No luck here either with the v0.21.9 beta. Still getting an error message that something went wrong when trying to use my yubikey with google.

**Comment by evq** [comment]
@cannedshrimp what OS are you trying with?

**Comment by cannedshrimp** [comment]
Running MarCOs High Sierra v10.13.3

**Comment by chmanie** [comment]
Same here. I’d be happy to help and debug this further (given the instructions)

**Comment by evq** [comment]
It looks like there is a Mac specific issue, I was able to confirm it as working on Windows and Linux but Mac also did not work for me. Thanks for your help testing, I will investigate more.

**Comment by lamaral** [comment]
I tried it on Windows 10, with the version linked above and it didn't work with the Yubico test page: https://demo.yubico.com/start/u2f/neo?tab=register.
It worked with GitHub and Google tho. 

Just to add on the discussion, I once had trouble with Google and Firefox and read somewhere that Google implements the U2F part slightly different from the standard and that's what broke Firefox.

**Comment by evq** [comment]
@lamaral Interesting, that test site also doesn't work for me. However https://demo.yubico.com/u2f does

**Comment by lamaral** [comment]
@evq This site works for me.

**Comment by bijeebuss** [comment]
Any updates on this? Mine setup does not work (confirmation does not appear on device)

Ubuntu Desktop 16.04 LTS
Ledger Nano S Firmware 1.4.1
Brave 0.21.18

It does work with the same setup and chrome

**Comment by evq** [comment]
Hey @bijeebuss. U2F support was moved back to our current beta channel release, `0.22` - I believe it is no longer present in `0.21`. Please let me know if you have an issue if you try `0.22`.

P.S. As an update to others, the mac specific issue mentioned above was resolved in https://github.com/brave/browser-laptop/pull/13345, so as of beta version `0.22.5` U2F has been tested / confirmed as working on Windows, MacOS and Linux.

Thanks all!

**Comment by cannedshrimp** [comment]
I can confirm U2F working on Google with the new Beta release on Mac High Sierra! Also worked on https://demo.yubico.com/u2f

Nice job!

**Comment by srirambv** [comment]
Verified on Windows x64

0.22.6 e6ff4ea
libchromiumcontent: 65.0.3325.162
muon: 5.1.0
Test plan works but still have issues relating to other domain login (#13564)

**Comment by krmbzds** [comment]
I couldn't get Github or YubiKey Demo to work.

#### OS Details
```
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202
````

#### Browser Details
```
Brave: 0.22.721 
V8: 6.6.346.32 
rev: bfe7cdd026c68013236ebe206a33448db9370fca 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170
```

Newly formatted computer so it's mostly a default setup.

**Comment by kylerchin** [comment]
I really need this, the only thing stopping me from using brave full time.
