### ISSUE TITLE
Follow-up to #5724: the bravery panel should be much wider

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5726]
## Test plan

1. Change the lang setting
2. Restart the browser
3. Open bravery panel on a site
4. Make sure the strings are not wrapped

----

#5724 #5715 

on macOS

1. Set your lang setting to Japanese
2. Restart the browser
2. Open https://github.com/brave/browser-laptop/issues/new

<img width="485" alt="screenshot 2016-11-18 19 38 20" src="https://cloud.githubusercontent.com/assets/3362943/20427364/e9cd5348-adc6-11e6-8666-2f053d0bcd81.png">

The panel should be much wider. It is too small for Japanese, at least. 

By setting ``width: 540px`` you would get:

<img width="549" alt="screenshot 2016-11-18 19 43 56" src="https://cloud.githubusercontent.com/assets/3362943/20427465/6825a9ac-adc7-11e6-9284-a5743b2fa8cc.png">

I have not tested it on other language settings, so I am not sure if it could work globally.

**Comment by luixxiul** [comment]
Here is the bug:

<img width="68" alt="screenshot 2016-11-18 19 53 22" src="https://cloud.githubusercontent.com/assets/3362943/20427728/afe0c8c0-adc8-11e6-8ac0-eb0a36b434b2.png">

the last character is partly hidden.

**Comment by srirambv** [comment]
This is actually a problem when changed to other languages. For example in Portugese(Brasil), the text is not completely shown and FP and Malware text is all moved to next line. 

![image](https://cloud.githubusercontent.com/assets/17010094/20428000/b68d22da-ad7e-11e6-8af0-474d9a03243c.png)

**Comment by luixxiul** [comment]
That bug must have existed since the new bravery panel was implemented #1951

**Comment by luixxiul** [comment]
The issue will be finally fixed with the compact panel:

<img width="313" alt="screenshot 2017-05-22 2 28 44" src="https://cloud.githubusercontent.com/assets/3362943/26286030/758dff30-3e96-11e7-9d0a-88720aaabe14.png">

**Comment by luixxiul** [comment]
As long as we use the fixed width, that thing can happen.

**Comment by luixxiul** [comment]
so my conclusion was: make the panel more large, or align the stuff vertically, and I took the latter.

**Comment by bbondy** [comment]
Moving to 0.18.x

**Comment by srirambv** [comment]
This is still an issue on the default shields panel unless we make the narrow panel as default. But for Russian even the narrow panel is as big as the default panel 
![image](https://user-images.githubusercontent.com/17010094/27368072-6596e6d6-5648-11e7-9c18-132572b93571.png)

**Comment by luixxiul** [comment]
I could set the text-ellipsis to the labels but I didn't because that's the important information and I thought we should not hide them even partially.

@bradleyrichter what do you think on that? Is it OK to set text-ellipsis to the labels?

**Comment by bradleyrichter** [comment]
Unfortunately we will need to copy-fit the longest strings. 

@aubrey - do you have a way of requesting max-length strings from translators in the current system?
