### ISSUE TITLE
Cannot login to Google Account with Google Prompt 2FA

### ISSUE THREAD

**Issue by mouse-man** [brave/browser-laptop#7866]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
When signing in to Google Account, I have 2FA set with Google Prompt being the primary. When logging in, the prompt goes to phone, but before I can approve, says 2FA failed. Have to use another 2FA method to login.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win8.1, Win10
- Brave Version (revision SHA):
Brave: 0.13.5 
rev: 1db81cb18b6919535792bb7e198ab87276bd67ea 
Muon: 2.56.8 
libchromiumcontent: 56.0.2924.87 
V8: 5.6.326.50 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: win32 
os.release: 6.3.9600 
os.arch: x64

- Steps to reproduce:
    1. Login to Google Account
    2. Get prompt
    3. Get Denied message
    
- Actual result:
Denied access
- Expected result:
Granted Access
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes, has happened on 2 machines.
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Will record next time I try this.
- Any related issues:

**Comment by philkloose** [comment]
I've got the same issue -- Brave browser shows immediate 2FA failure although my phone receives (Yes|No) prompt successfully.  I have to fall back to Google Authenticator.  Other details identical except for OS which is Win 7 (x64).

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/gmail-2fa-authentication-not-working-when-shield-is-up/3532

**Comment by LaurenWags** [comment]
+1 from community (see # 16 in this post: https://community.brave.com/t/issue-small-bugs-found-in-first-couple-hours-of-using-brave/5075)

**Comment by luixxiul** [comment]
+1 https://github.com/brave/browser-laptop/issues/10579

**Comment by deive** [comment]
Also getting this with Chrome Version 60.0.3112.113 and Android.
Chrome instantly shows “Your sign-in attempt timed out. Resend the prompt to try again.” and does not react when I tap yes on the phone

**Comment by volcani** [comment]
I also getting in with resembling problem.
"One tap auth" doesn't work.
When I get prompt from google to my phone,  brave shows me "time out" dialogue without second.

My enviroment is 

Wiindows10 32bit
brave 0.19.53 reve09025b

Strangely, google chrome on same device works normaly.
Only brave deny my access.

**Comment by winteraz** [comment]
I'm developing a http proxy and for some reasons  I have the same error with "One tap auth" regardless of the browser. Any idea what might cause that?

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/google-prompt-sign-in-immediately-timed-out-on-youtube/11607

**Comment by srirambv** [comment]
+1 from #12196

**Comment by thereseng** [comment]
Same problem here. Need to use Google Authenticator

**Comment by bbw22** [comment]
This is definitely still a problem in normal tabs and private tabs. End up having to use sms to authenticate.

**Comment by freimer** [comment]
I have a slightly different issue, but related.  2FA does not work in Brave even with shields down when using a Yubikey:

Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

This is for github, gitlab, and basically any 2FA site I tried.  It works perfectly fine in Chrome.
Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by csleary** [comment]
@freimer Yeah, Brave doesn't seem to support Fido U2F, as the Yubikey won't flash to prompt. 🙁

**Comment by freimer** [comment]
Actually, this works with brave-beta...

**Comment by bsclifton** [comment]
This may have been fixed with https://github.com/brave/browser-laptop/issues/11401 in 0.22.x (if you imported from Chrome)

For folks experiencing this: can you please try our 0.22.x release?
https://github.com/brave/browser-laptop/releases/tag/v0.22.9dev

**Comment by csleary** [comment]
@bsclifton Does indeed sort it. Thanks Brian!

**Comment by bsclifton** [comment]
@csleary awesome! I'll close this issue for now- let's re-open if 0.22.x does not work for you (as @freimer mentioned, beta is on the 0.22.x version, which is why it worked)

**Comment by DanEhrlich** [comment]
Still hapenning
 
Brave: 0.22.22 
V8: 6.5.254.41 
rev: 63033109963be0a995b3d1ed9723870beeb191c4 
Muon: 5.1.2 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Comment by kaibakker** [comment]
I still have the issue aswell, I have the beta right?

Brave | 0.22.669
-- | --
V8 | 6.6.346.24
rev | 6cda2e8
Muon | 5.2.7
OS Release | 15.6.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.117

**Comment by garrettr** [comment]
Reproducible on 0.22.714.

**Comment by Captain-Chaos** [comment]
Still happening on 0.22.721 on Xubuntu 18.04.

**Comment by gymnastboatman** [comment]
Still happening to me. Android, 1.0.48, chromium 66.0.3359.158 

7.1.1, build NMF26V

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/google-inbox-login-with-2fa-using-google-app-on-iphone-not-working-properly/23976

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/brave-cant-login-with-google-tap-your-smartphone-feature/26460?u=eljuno

**Comment by stevemdavies** [comment]
Why is this closed? This is still an issue


Brave | 0.23.31
-- | --
V8 | 6.7.288.46
rev | 3148ace
Muon | 7.1.5
OS Release | 17.5.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

**Comment by zeroxxx2** [comment]
How's this closed? The crap's still going on. If you can't fix it don't close it. Incompetent.

**Comment by bsclifton** [comment]
@zeroxxx2 it's not closed actually. It was thought that a patch earlier this year fixed it (which it didn't) and the issue was re-opened (back in May)

**Comment by bsclifton** [comment]
...and then again right now, because I clicked the wrong button 😛

**Comment by scgruber** [comment]
I just came here after encountering this issue. I was able to work around by setting Cookie Control to **Allow all cookies** for accounts.google.com, after which my two-factor push immediately started working.

> Brave: 0.23.79 
> V8: 6.8.275.24 
> rev: 51b49051a779f0db94fbcfd0df5faca781299ea0 
> Muon: 8.0.7 
> OS Release: 4.4.0-130-generic 
> Update Channel: Release 
> OS Architecture: x64 
> OS Platform: Linux 
> Node.js: 7.9.0 
> Brave Sync: v1.4.2 
> libchromiumcontent: 68.0.3440.84

**Comment by erasmus** [comment]
Still there in `v0.24.0`
<img width="540" alt="screen shot 2018-09-21 at 11 15 25" src="https://user-images.githubusercontent.com/1915920/45884978-83a29280-bdb5-11e8-97b2-8a5583fbde96.png">

**Comment by bsclifton** [comment]
For folks experiencing this problem: can you please try out new Beta release?
https://brave.com/download-beta

You should be able to import everything from your existing Brave install (except Brave Payments- for that, you'd want to export your wallet). The problem should be fixed there

Unfortunately, I don't think we'll be able to address this issue with this code-base. My recommendation would be to try the Beta and if the problem persists, let me know and I can help create an issue in our new repository:
https://github.com/brave/brave-browser

**Comment by bsclifton** [comment]
Looks like this is possibly still an issue in our new code-base; issue is being tracked with https://github.com/brave/brave-browser/issues/1356

**Comment by TheGorf** [comment]
Can confirm. Experiencing this issue as of this morning.
 
Brave: 0.25.2 
V8: 6.9.427.23 
rev: 8ea2a9ce5ca329478186e6393e07f1cf87d34a22 
Muon: 8.1.8 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Comment by stenmuchow** [comment]
@bsclifton Beta works as it should...
