### ISSUE TITLE
Crash reporting not enabled for Windows build

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7917]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Crash reporting not enabled for Windows build

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	61b6b6b

- Steps to reproduce:
    1. Do a clean install of 0.14.0 preview 7
    2. Launch browser from console, doesn't show `Crash reporting enabled`
    3. Enable payments from settings causing browser to crash(#7911), no log shown in console
    
- Actual result:
No logs shown when browser crash due to crash reporting disabled

- Expected result:
Crash reporting should be enabled to capture logs for browser crash

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![7911-1](https://cloud.githubusercontent.com/assets/17010094/24365968/9780bf4a-130f-11e7-87f5-2e1ee379a97c.gif)

- Any related issues:

**Comment by aekeus** [comment]
cc @bridiver and @alex as this could be muon related

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/632be42ce34e964101d88a2aee892a352913a8d9

**Comment by luixxiul** [comment]
Is there any good QA steps, as the original issue to cause the crash has been fixed?

**Comment by srirambv** [comment]
Still don't see logs in console on the RC1 build.

**Comment by NejcZdovc** [comment]
@srirambv fix from @darkdh is included in muon 2.57.7, RC1 has muon 2.57.6

**Comment by darkdh** [comment]
@luixxiul , I think just need to verify you have `Crash reporting enabled` shown when you start Brave from console

**Comment by srirambv** [comment]
Works fine when launched from git bash shell. Windows Command prompt still doesn't show the info
