### ISSUE TITLE
bookmarks not fitting in the bookmark bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9939]
## Test plan
See https://github.com/brave/browser-laptop/pull/12768

## Original issue description
**Describe the issue you encountered:** https://community.brave.com/t/bookmarks-toolbar-management/4396/13?u=suguru

> When I recently transitioned to Brave, I imported my FF Bookmarks and set up all the Bookmarks I wanted on the Bookmarks Toolbar, with 17 Bookmarks on the Toolbar (plus the Bookmarks Folder Icon which can't be removed apparently). Suddenly within the past couple of days only 9 of the Bookmarks appear in the Toolbar and the remaining 8 can only be accessed by clicking on the ">>" icon at the far right of the bar, even though there's plenty of real estate there and they all fit in the bar before. 
>
> ![](https://cdn-standard2.discourse.org/uploads/brave/optimized/2X/3/374984b450fcc97c33a4c6a8c2006d98e3b1c3a1_1_690x182.jpg)

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA): Windows 7 Pro

- Steps to reproduce: See above

- Actual result: See above

- Expected result:

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by indigion** [comment]
Also an issue for me, but I have 40 bookmarks in the imported toolbar and when I click on the >> to get the list displayed there is a delay in loading the list and thereafter a 5 sec or so delay in mouse response. That is the highlighted bookmark takes 5 secs to update to reverse color to show where the mouse is.  Makes this unusable.

Also I can only scroll to the bottom of my list )which is initially off the bottom of the screen) as I have a wheel on my mouse. Without this I cannot see how I could scroll the list content. I would expect moving the mouse pointer to near the bottom would auto-scroll the list (as happens in Firefox).

Also gets confusing if I then leave the mouse and use keyboard arrow keys to navigate the list. I get two separate bookmarks highlighted.

**Comment by stevedee** [comment]
I also only see bookmarks across the first half of the bar. Bookmarks which should appear beyond the half-way point, appear in the drop-down list (>>).
This only started a couple of weeks ago.

Todays update did not fix.

Current system:-
 
Brave: 0.17.19 
rev: 4e46480 561da44d76d6ee4c60d6979df80d339f8 
Muon: 4.1.9 
libchromiumcontent: 59.0.3071.115 
V8: 5.9.211.38 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.10.0-28-generic 
os.arch: x64

**Comment by farfel** [comment]
I keep reverting back to version 0.16.9 because of this same (mildly annoying...) problem.

The bookmarks toolbar rendering has been broken for me in all subsequent releases, as I've tried them all with ever increasing hope that the next version will fix it.

The above issue aside, Brave is my default browser. Keep up the good work!

I'm on macOS Sierra 10.12.6.

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/toolbar-hiding-bookmarks-when-theres-plenty-of-space/5392/)

Mac OS Sierra 10.12.6

Brave version:
Brave: 0.18.14
rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8
Muon: 4.3.6
libchromiumcontent: 60.0.3112.78
V8: 6.0.286.44
Node.js: 7.9.0
Update Channel: dev
OS Platform: macOS
OS Release: 16.7.0
OS Architecture: x64

**Comment by LaurenWags** [comment]
+1 from community https://community.brave.com/t/bookmark-problem/6128

**Comment by NejcZdovc** [comment]
I think that this will be fixed in 0.20 with this PR #10458

**Comment by luixxiul** [comment]
+1 from https://github.com/brave/browser-laptop/issues/10594 (Bookmarks Toolbar Not Fully Utilized)

**Comment by benjusmaximus** [comment]
I'm getting the same problem in the latest version for mac. 15 bookmarks show in the bar, with about half the bar as free space. Any extra bookmarks I add, end up under the arrow menu on the right. 
![screen shot 2017-08-28 at 7 40 34 pm](https://user-images.githubusercontent.com/31404585/29768338-352001a6-8c29-11e7-9d79-53f8aef65b2f.png)
Sounds like it's being attended to. Looking forward to the fix. Many thanks

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bookmarks-bar-only-showing-halfway-on-its-row/7361?u=eljuno

**Comment by MusicallyInspired** [comment]
Same issue. Just started using Brave and I love it and love what it stands for. But I'd love for this to be fixed as it's quite annoying. Only qualm so far.

Brave | 0.18.29
rev | 85f059d
Muon | 4.3.16
libchromiumcontent | 60.0.3112.113
V8 | 6.0.286.56
Node.js | 7.9.0
Update Channel | dev
OS Platform | Microsoft Windows
OS Release | 10.0.10586
OS Architecture | x64

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bookmarks-toolbar-dont-fill-up-to-right/8079?u=eljuno

 Brave 0.18.36 rev 7ab85e9
MacBook Pro 13" late 2013 with OSX 10.12.6.

**Comment by johnlm1** [comment]
+1 from me

Bookmark bar only fills up halfway before it starts hiding additional ones on the far right side (as though the bookmark bar was full).

 
Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: macOS 
OS Release: 17.0.0 
OS Architecture: x64

**Comment by NejcZdovc** [comment]
should be fixed with #10325

**Comment by srirambv** [comment]
Happening intermittently, Confirmed not seen on macOS by @LaurenWags

**Comment by LaurenWags** [comment]
First time I tried it did not show (not a brand new profile, but was new today). Second time it did show (completely clean profile)

**Comment by srirambv** [comment]
This is still an issue on Linux
![12768](https://user-images.githubusercontent.com/17010094/35561552-ad9f4f5c-05d6-11e8-8adb-c9f55377dca2.gif)

**Comment by NejcZdovc** [comment]
I will close this one, because it's better and let's open another issue for linux only.
